# This version creates 3 postgres databases for Feast (main store, offline store, online store)
# Have the following environment vars set in shell before running docker-compose
# (suggested values here but can use whatever desired):
# export OFFLINE_PGDB_NAME=#
# export OFFLINE_PGDB_USER=#
# export OFFLINE_PGDB_PASS=#
# export OFFLINE_PGDB_PORT=#
# export ONLINE_PGDB_NAME=#
# export ONLINE_PGDB_USER=#
# export ONLINE_PGDB_PASS=#
# export ONLINE_PGDB_PORT=#

services:

    offline_pgdb:
        restart: always
        image: postgres:latest
        container_name: offline_pgdb
        ports:
            - ${OFFLINE_PGDB_PORT}:5432
        environment:
            - MUID=$UID
            - MGID=$GID
            - POSTGRES_DB=${OFFLINE_PGDB_NAME}
            - POSTGRES_USER=${OFFLINE_PGDB_USER}
            - POSTGRES_PASSWORD=${OFFLINE_PGDB_PASS}
        volumes:
            - offline_pgdb_data:/var/lib/postgresql/offline_pgdb_data

    online_pgdb:
        restart: always
        image: postgres:latest
        container_name: online_pgdb
        ports:
            - ${ONLINE_PGDB_PORT}:5432
        environment:
            - MUID=$UID
            - MGID=$GID
            - POSTGRES_DB=${ONLINE_PGDB_NAME}
            - POSTGRES_USER=${ONLINE_PGDB_USER}
            - POSTGRES_PASSWORD=${ONLINE_PGDB_PASS}
        volumes:
            - online_pgdb_data:/var/lib/postgresql/online_pgdb_data


volumes:
    offline_pgdb_data:
    online_pgdb_data:
